/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { regionSchema } from "../regions/region.output.js";

const appRouter = t.router({
  regionsRouter: t.router({
    findAll: publicProcedure
      .output(z.array(regionSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  healthRouter: t.router({
    health: publicProcedure
      .output(z.object({
  status: z.string(),
  message: z.string(),
}))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
