/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { registerInput } from "../auth/register.input.js";
import { authOutput } from "../auth/auth.output.js";
import { loginInput } from "../auth/login.input.js";
import { citiesByRegionInput } from "../cities/city.input.js";
import { citySchema } from "../cities/city.output.js";
import { regionSchema } from "../regions/region.output.js";

const appRouter = t.router({
  authRouter: t.router({
    register: publicProcedure
      .input(registerInput)
      .output(authOutput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    login: publicProcedure
      .input(loginInput)
      .output(authOutput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  citiesRouter: t.router({
    findByRegion: publicProcedure
      .input(citiesByRegionInput)
      .output(z.array(citySchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  regionsRouter: t.router({
    findAll: publicProcedure
      .output(z.array(regionSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  healthRouter: t.router({
    health: publicProcedure
      .output(z.object({
  status: z.string(),
  message: z.string(),
}))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
