/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from '@trpc/server';
import { z } from 'zod';

const t = initTRPC.create();
const publicProcedure = t.procedure;

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const appRouter = t.router({
  healthRouter: t.router({
    health: publicProcedure
      .output(
        z.object({
          status: z.string(),
          message: z.string(),
        }),
      )
      // eslint-disable-next-line @typescript-eslint/no-unsafe-return
      .query(() => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
});

export type AppRouter = typeof appRouter;
