// Helper file generated by shadcn
// Helper function combining 2 capabilities: 1. turning a list of values into a string 2. merging Tailwind classes, to avoid styling conflicts
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
